title: Kyle Munkittrick
description: Product manager, bioethicist, and technology writer. M.A. in Bioethics from NYU. Regular contributor to 3 Quarks Daily writing about AI, human enhancement, mortality, and technology ethics. Former PM at Amazon One Medical and One Medical.
url: "https://kmunk.com"
baseurl: ""

author:
  name: Kyle Munkittrick
  email: kmunkitt@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for fiction
collections:
  fiction:
    output: true
    permalink: /fiction/:title/

# Exclude files from processing
exclude:
  - README.md
  - CNAME

# Permalink structure for posts
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Social links
social:
  linkedin: kylemunkittrick
  email: kmunkitt@gmail.com

# SEO settings
twitter:
  username: # add if you have twitter
  card: summary_large_image

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Kyle Munkittrick"